apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - poddisruptionbudget.yaml
  - hpa.yaml
  - networkpolicy.yaml

patches:
  - path: replica-patch.yaml
  - path: db-patch.yaml
  - path: remove-h2-pvc.yaml
