apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eximeebpms-database-h2
  labels:
    app.kubernetes.io/name: eximeebpms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
